stages:
  - build

build_image:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      command: ["--insecure-registry=registry.gitlab.com"]
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${DOCKER_HUB_USER}/${CI_PROJECT_NAME}
  after_script:
    - docker push ${CONTAINER_IMAGE}
    - docker push ${DOCKER_HUB_USER}/${CI_PROJECT_NAME}
